#!/bin/sh
# SH FILE: build
#
# Purpose   : Byte compile package.
# Created   : Tuesday, November 11 2025.
# Author    : Pierre Rouleau <prouleau001@gmail.com>
# Time-stamp: <2025-11-24 11:40:48 EST, updated by Pierre Rouleau>
# ----------------------------------------------------------------------------
# Module Description
# ------------------
#
# A simple build script that converts the tbindent.el into tbindent.elc
# doing it in isolation.

# ----------------------------------------------------------------------------
# Dependencies
# ------------
#
# None.

# ----------------------------------------------------------------------------
# Code
# ----
#
#

set -x
emacs -Q  --batch -L . --eval '(setq byte-compile-error-on-warn t)' -f batch-byte-compile tbindent.el

# ----------------------------------------------------------------------------
